# First, let's install Pytorch

In [2]:
!pip3 install -q http://download.pytorch.org/whl/cu90/torch-0.4.0-cp36-cp36m-linux_x86_64.whl

In [3]:
!pip3 install torchvision

  Using cached https://files.pythonhosted.org/packages/ca/0d/f00b2885711e08bd71242ebe7b96561e6f6d01fdb4b9dcf4d37e2e13c5e1/torchvision-0.2.1-py2.py3-none-any.whl


# Check if Pytorch is already installed

In [4]:
import torch
print(torch.__version__)
x = torch.rand(5, 3)
print(x)

0.4.0
tensor([[ 0.6752,  0.3122,  0.6386],
        [ 0.4139,  0.3470,  0.1569],
        [ 0.4539,  0.8427,  0.8945],
        [ 0.5773,  0.6610,  0.0795],
        [ 0.0725,  0.6064,  0.7266]])


# Check if we can use GPU

In [5]:
import torch

# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print("No GPU available!")

tensor([[ 1.6752,  1.3122,  1.6386],
        [ 1.4139,  1.3470,  1.1569],
        [ 1.4539,  1.8427,  1.8945],
        [ 1.5773,  1.6610,  1.0795],
        [ 1.0725,  1.6064,  1.7266]], device='cuda:0')
tensor([[ 1.6752,  1.3122,  1.6386],
        [ 1.4139,  1.3470,  1.1569],
        [ 1.4539,  1.8427,  1.8945],
        [ 1.5773,  1.6610,  1.0795],
        [ 1.0725,  1.6064,  1.7266]], dtype=torch.float64)
